### ISSUE TITLE
Beta-Program for Actions

### ISSUE THREAD

**Issue by signalwerk** [satelliteworkshops/integrate-2-making-github-actions-actionable#3]
Hey @nholden 
Sorry to bother you. I've been to Github-Satellite last week in Berlin. Great organisation, awesome workshops and exciting talks! You mentioned the people attending your workshop would be enrolled in the beta-program for github-actions. Is that still planned? I would really love to try it.  I also spoke to @krider2010 and she mentioned there should be a process for it. Do I have to do something?

**Comment by krider2010** [comment]
Hey @signalwerk - sorry for the delay. This is totally on us. Our remote team has been scattering since Friday back around the globe. Also yesterday was a bank holiday in the UK and Memorial Day in the US so a bunch of us were on Vacation.

I've already dropped your name (and others) to the Actions product manager, and will follow up again with her today 👍

**Comment by signalwerk** [comment]
Hey @krider2010 
Thank you for the information and the follow up. Thats really good to hear! I didn't wanna be the one who's pulling everyones leg. Sorry for that! You guys do awesome!
